name: ccb-solidjs-platform
services:
  # Frontend SolidJS
  - name: frontend
    source_dir: /
    github:
      repo: tu-usuario/ccb-solidjs-platform
      branch: main
    run_command: npm start
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /
    envs:
      - key: VITE_API_URL
        value: ${backend.PUBLIC_URL}
      - key: VITE_VUE_SYSTEM_URL
        value: https://tu-vue-system.com

  # Backend Node.js
  - name: backend
    source_dir: /backend
    github:
      repo: tu-usuario/ccb-solidjs-platform
      branch: main
    run_command: npm start
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /api
    envs:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "8080"
      - key: MONGODB_URI
        value: ${ccb-mongodb.CONNECTION_STRING}
      - key: REDIS_URL
        value: ${ccb-redis.CONNECTION_STRING}

databases:
  - name: ccb-mongodb
    engine: MONGODB
    version: "5"
    size: basic-xs

  - name: ccb-redis
    engine: REDIS
    version: "7"
    size: basic-xs 